# Generated by Django 2.1.5 on 2019-01-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
