# Generated by Django 2.1.5 on 2019-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_auto_20190122_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
