# Generated by Django 2.1.5 on 2019-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('nature', models.CharField(choices=[('EN', 'Entry'), ('EG', 'Egress')], default='EN', max_length=2)),
            ],
        ),
    ]
